### ISSUE TITLE
Duplicate operation IDs in swaggerV2.json

### ISSUE THREAD

**Issue by gbrueckl** [Microsoft/powerbi-rest-api-specs#6]
some of the operation ID exist twice which causes an error when trying to import the Swagger Meta Data into VS.
Most of the API Call exist twice, for MyWorkspace and for Groups but the OperationIDs have not been update correctly

**Comment by ali-hamud** [comment]
Fixed in this commit:
https://github.com/Microsoft/powerbi-rest-api-specs/commit/8dbfd5ed3020c5054b543f9986d6f5b325bd1d9c

Thank you for opening this issue.
